create extension if not exists pgcrypto;

create or replace function public.set_site_signup_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.community_invitations (
  id uuid primary key default gen_random_uuid(),
  email text not null check (char_length(email) between 3 and 320),
  email_normalized text generated always as (lower(btrim(email))) stored,
  source text not null default 'website' check (char_length(source) <= 80),
  status text not null default 'waiting' check (status in ('waiting', 'invited', 'active', 'unsubscribed')),
  email_updates boolean not null default true,
  unsubscribe_token uuid not null default gen_random_uuid(),
  confirmation_email_sent_at timestamptz,
  last_email_sent_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_invitations_email_normalized_key unique (email_normalized),
  constraint community_invitations_unsubscribe_token_key unique (unsubscribe_token)
);

create table if not exists public.headsup_beta_signups (
  id uuid primary key default gen_random_uuid(),
  email text not null check (char_length(email) between 3 and 320),
  email_normalized text generated always as (lower(btrim(email))) stored,
  platform text not null default 'either' check (platform in ('android', 'ios', 'either')),
  source text not null default 'website' check (char_length(source) <= 80),
  status text not null default 'waiting' check (status in ('waiting', 'invited', 'testing', 'unsubscribed')),
  email_updates boolean not null default true,
  unsubscribe_token uuid not null default gen_random_uuid(),
  confirmation_email_sent_at timestamptz,
  last_email_sent_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint headsup_beta_signups_email_normalized_key unique (email_normalized),
  constraint headsup_beta_signups_unsubscribe_token_key unique (unsubscribe_token)
);

create table if not exists public.signup_email_log (
  id bigint generated by default as identity primary key,
  audience text not null check (audience in ('community', 'headsup-beta')),
  subscriber_id uuid not null,
  recipient_email text not null,
  email_kind text not null check (email_kind in ('confirmation', 'update')),
  campaign_id text,
  resend_email_id text,
  delivery_status text not null default 'submitted',
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.site_signup_rate_limits (
  fingerprint_hash text not null,
  window_start timestamptz not null,
  attempts integer not null default 1,
  primary key (fingerprint_hash, window_start)
);

drop trigger if exists community_invitations_updated_at on public.community_invitations;
create trigger community_invitations_updated_at
before update on public.community_invitations
for each row execute function public.set_site_signup_updated_at();

drop trigger if exists headsup_beta_signups_updated_at on public.headsup_beta_signups;
create trigger headsup_beta_signups_updated_at
before update on public.headsup_beta_signups
for each row execute function public.set_site_signup_updated_at();

create or replace function public.consume_site_signup_rate_limit(
  p_fingerprint_hash text,
  p_limit integer default 8
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_window timestamptz := date_trunc('hour', now());
  v_attempts integer;
begin
  delete from public.site_signup_rate_limits
  where window_start < now() - interval '48 hours';

  insert into public.site_signup_rate_limits (fingerprint_hash, window_start, attempts)
  values (p_fingerprint_hash, v_window, 1)
  on conflict (fingerprint_hash, window_start)
  do update set attempts = public.site_signup_rate_limits.attempts + 1
  returning attempts into v_attempts;

  return v_attempts <= greatest(p_limit, 1);
end;
$$;

alter table public.community_invitations enable row level security;
alter table public.headsup_beta_signups enable row level security;
alter table public.signup_email_log enable row level security;
alter table public.site_signup_rate_limits enable row level security;

revoke all on public.community_invitations from anon, authenticated;
revoke all on public.headsup_beta_signups from anon, authenticated;
revoke all on public.signup_email_log from anon, authenticated;
revoke all on public.site_signup_rate_limits from anon, authenticated;
revoke all on function public.consume_site_signup_rate_limit(text, integer) from public, anon, authenticated;

grant select, insert, update, delete on public.community_invitations to service_role;
grant select, insert, update, delete on public.headsup_beta_signups to service_role;
grant select, insert, update, delete on public.signup_email_log to service_role;
grant select, insert, update, delete on public.site_signup_rate_limits to service_role;
grant usage, select on sequence public.signup_email_log_id_seq to service_role;
grant execute on function public.consume_site_signup_rate_limit(text, integer) to service_role;

create index if not exists community_invitations_status_updates_idx
  on public.community_invitations (status, email_updates);
create index if not exists headsup_beta_signups_status_updates_idx
  on public.headsup_beta_signups (status, email_updates);
create index if not exists signup_email_log_subscriber_idx
  on public.signup_email_log (subscriber_id, created_at desc);
